### ISSUE TITLE
Europa Universalis 4 does not run with Mangohud enabled

### ISSUE THREAD

**Issue by RaduAvramescu** [flightlessmango/MangoHud#1303]
**Describe the bug**
After pressing "Play" on Steam, Europa Universalis 4's launcher appears. When pressing "Play" in the game's launcher, an error window appears and the game does not run.

**List relevant hardware/software information**
- Linux Distribution: Fedora 40 Beta (KDE spin)
- Kernel: 6.8.7-300.fc40.x86_64
- Mesa: 24.1.0
- MangoHud version: mangohud-0.7.1-3.fc40.x86_64
- Steam: rpm
- KDE Plasma Version: 6.0.3
- KDE Frameworks Version: 6.0.0
- Qt Version: 6.6.2
- Graphics Platform: Wayland
- GPU: AMD RX 7900 XTX

**To Reproduce**
1. Launch the application
2. In the launcher, press "Play"
3. Observe the error window

**Expected behavior**
The game should launch after pressing "Play" in the game's launcher, without producing an error.

**Screenshots**
![Screenshot_20240421_115930](https://github.com/flightlessmango/MangoHud/assets/71271545/fb5995c7-ec55-4d9d-ba4f-2db7c2dccfd1)

**Additional context**
If I press the "Show details" button from the error window, this is the output:
```
ERROR: ld.so: object '/home/REDACTED/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/REDACTED/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
[2024-04-21 11:33:02.482] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/home/REDACTED/.config/MangoHud/presets.conf'
```

**Comment by flightlessmango** [comment]
Works fine on my end. It's possible it's been fixed in recent versions
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/b6594315-8ada-4ee4-a7be-b3d39b394dcf)

**Comment by RaduAvramescu** [comment]
I've tried a few things but I didn't really get anywhere. Added `--dlsym` as a launch parameter, and that exhibited the same issue.

Running with `MANGOHUD_LOG_LEVEL=DEBUG` as well didn't output anything that could be interesting, from what I could tell.

@flightlessmango I ran the game with its native Linux build - haven't tried Proton and I'm not interested in trying it out yet. Based on your screenshot, you also ran native?

**Comment by fallenexistence0** [comment]
Run steam from the terminal then run your game, when you get the error exit steam, the terminal might give us an exact error, or at least where the problem is happening.

Try disabling the steam overlay for europa and then launching the game, that might solve the issue for you.

You can also try using another launcher such as heroic or lutris, and adding the game to those launchers, you'll have the option of using different wine versions (as well as proton-ge). Experiment with different versions and show us the results.

**Comment by mentaldust** [comment]
I've told you about a similar error before, If you can remember. It was happening on the Stellaris launcher too on Fedora 39 KDE. Now that I am on a fresh install of Fedora 40 KDE, it is still happening.

**Comment by RaduAvramescu** [comment]
@fallenexistence0 I've already tried disabling the Steam overlay for EU4, which unfortunately didn't work.

As for running Steam from the terminal, there is no terminal output when that error in the game's launcher appears. The launcher can still be interacted with as well (I can press "Play" again, and the same error pops up, for example, but nothing new in the terminal).

Running the game with both Sway and Hyprland produces the same issue (this is from the same KDE install though, so it's not the Sway spin of Fedora nor a minimal install with Hyprland).

I'll wipe my install and try out Fedora 40 Workstation. I'll come back with an update regarding whether or not MangoHud worked for EU4 there.

**Comment by RaduAvramescu** [comment]
I'm experiencing the same issue after a fresh install of Fedora Workstation 40 (so, this is Gnome), with fully up to date packages, and just mangohud and Steam installed (both from rpms). The Mangohud version is still v0.7.1, kernel is 6.8.8, and Mesa 24.0.6. Again, this is the native Linux build of EU4 (maybe the Proton version works but I'd rather not resort to that).

It looks like it's not DE specific, but maybe Fedora specific? Or perhaps a newer version fixed the issue, as @flightlessmango noted.

**Comment by flightlessmango** [comment]
Closing until it can be verified that the bug exists in 0.7.2

**Comment by RaduAvramescu** [comment]
Hello @flightlessmango,

Sorry, I didn't have time to retest.

I just reinstalled Fedora, and am using Hyprland again, on kernel 6.9.5-200.fc40.x86_64, mesa-git and mangohud 0.7.2.

Unfortunately, I still get an error when trying to start the game from the launcher.

**Comment by flightlessmango** [comment]
I can't repro this with similar setup, except I'm using arch.
It's strange that mangohud is showing in the launcher however, that should have been blacklisted since long ago

**Comment by RaduAvramescu** [comment]
@flightlessmango Well, I can actually post an update regarding the launcher.

I no longer see Mangohud in the launcher (not sure if this was the case yesterday as well or if I just noticed it today), so I think this is good at least, and there is some progress. I suppose this was fixed between 0.7.1 and 0.7.2.

That said, I'm still getting the error. For further information, I'm using the Steam rpm, along with these launch options:
`gamemoderun mangohud --dlsym %command%`

I've tried removing `gamemoderun` and `--dlsym` just for testing purposes and neither worked (whether both of them are removed or just one of them didn't matter).

**Comment by pruebahola** [comment]
I can confirm that is happening to me too from the moment that I updated mangohud  to 0.7.2

Was not happening in 0.7.1

but my experience is with **Total War Warhammer 3** ( I don't have Europa Universalis 4) but the issue is the same

In the launcher Mangohud Work, but when i click in Play, steam show are running the game but nothing happen and i don't get any log

**Comment by RaduAvramescu** [comment]
@pruebahola I believe you have to enable Mangohud differently for the Steam Flatpak - this may be a different, unrelated issue.

You should use Flatseal to add `MANGOHUD=1` env variable to Steam, or alternatively, this command:
```
flatpak override --user --env=MANGOHUD=1 com.valvesoftware.Steam
```

Then remove `mangohud %command%` from your launch options.

**Comment by pruebahola** [comment]
@RaduAvramescu man... this is not a new installating, i did that months ago and MangoHUD work perfectly fine in my others games and even work in the Launcher for Total War Warhammer 3

The problem is when you click play in the launcher... the game don't open if Mangohud is enable

**Comment by 9-Extra** [comment]
I am getting the same problem running native Linux Stellaris. But interestingly, the crash only happens when I use the **NVIDIA GPU**. When I switch to the Intel integrated GPU, both the game and mangohud works fine. 
I am using KDE6 on Wayland.  NVIDIA Driver Version 565.77.

**Comment by 9-Extra** [comment]
The same problem happens running native Linux Stellaris. But interestingly, only on my **NVIDIA GPU**. After switching to the Intel integrated GPU, both the game and MangoHud work just fine.
Using KDE6 on Wayland. NVIDIA Driver Version 565.77, MangoHud 0.7.2.

**Comment by flightlessmango** [comment]
It's possible this is resolved in 0.8.0-rc2

**Comment by flightlessmango** [comment]
Assuming fixed
