### ISSUE TITLE
CPU Temperature not working

### ISSUE THREAD

**Issue by TateFleming** [flightlessmango/MangoHud#868]
I have a Ryzen 9 7900X CPU. Lm-sensors does not report the CPU sensor stats, so this tool fails on it. Hopefully this will be supported in the future. In the meantime, I put in a work around (just look at nvme temperature instead of cpu) so the program still functions.

Another problem was the program looking for hwmon directories in the incorrect locations. I put in a quick-fix that works for my build, so I can now display full GPU stats.

If anyone runs into these issues and needs help, feel free to reach out. Better yet, if anyone has solutions to these problems, please let me know!

**Comment by gort818** [comment]
For the CPU temp, upgrade your kernel.

You had a problem displaying GPU stats?

**Comment by TateFleming** [comment]
Kernel is latest 5.15. No CPU stats reported from sensors, seems to be a known thing.

It was assuming GPU stats were at '/sys/class/drm/card0-HDMI-A-1/device/hwmon/' which returned an error. The stats are actually in '/sys/class/drm/card0-HDMI-A-1/device/device/hwmon/.' I don't know if this is something specific to my build or if it is new with Zen4. I'm new to all of this myself, so I could be doing something incorrectly.

**Comment by gort818** [comment]
That kernel is over a year old, I believe the monitor for those cpus was added about 5 months to the kernel.

Those are harmless errors, we iterate over the files to find the right one

**Comment by TateFleming** [comment]
Now kernel is 6.1.0. CPU temperature updates, but all GPU stats are messed up now.

**Comment by gort818** [comment]
What GPU, what exactly is messed up?

**Comment by TateFleming** [comment]
GPU is Radeon RX6600.

I'm trying to display CPU and GPU stats, temp, power. Also GPU core and mem clocks, and CPU mhz.

GPU showing 0%, cooler than expected temperature, constant 65535MHz for one of the clocks, and ~10W power. I have two amdgpu items that show up when 'sensors' is ran, it appears that MangoHud is grabbing the second when it should grabbing the first potentially?

CPU stats are good besides temperature is stuck at 655C.

VRAM displays 0.0GiB.

**Comment by gort818** [comment]
are you on the latest build of MangoHud?

**Comment by TateFleming** [comment]
Yes I am. I just removed it completely and cloned the repo again to verify.

**Comment by gort818** [comment]
7900X has an igpu doesn't it? 

can you try this?
https://github.com/flightlessmango/MangoHud/issues/802#issuecomment-1186574641

set `pci_dev` for your RX6600

**Comment by valeth** [comment]
I'm on a Ryzen 5 7600X and for me it's reading 655C temperature, doesn't sound quite right.
For the iGPU the reading seems to be correct though (but for that one the MHz one is slightly off, reading it as 65535MHz)

Tools like KDE's System Monitor seem to be able to read the temp correctly, so there's definitely kernel support.

Kernel: `6.1.4-x64v1-xanmod1-1`
Mangohud: `0.6.8`

**Comment by Daniel-Salvado** [comment]
I'm on Ryzen 9 7900x and it's also showing 655 degrees. [Screenshot](https://imgur.com/a/7ZCd74d)  
The KDE System Monitor and sensors show the correct temps. [Screenshot](https://imgur.com/a/oqUrsGF)  
  
Kernel Version: `6.0.18-300 (64-bit)`
Mangohud Version: `0.6.8-1`
OS: `Fedora 37`

**Comment by gort818** [comment]
Can someone with a zen4 show me the contents of the `temp1_input` file.

`grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_input'`

**Comment by valeth** [comment]
@gort818 returns `41000` for me

**Comment by gort818** [comment]
Thank you!
can you try this  patch?
[cpu.txt](https://github.com/flightlessmango/MangoHud/files/10419183/cpu.txt)

**Comment by gort818** [comment]
Also if someone can give me the output of this 
`grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_label'`

**Comment by Daniel-Salvado** [comment]
`grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_input'` returns different numbers (when called multiple times) the last ones were `33375, 33250, 33125, 33375`  
`grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_label'` always returns `Tctl`

**Comment by TateFleming** [comment]
I'm seeing similar outputs. Is this new to report the temperature in milli-Celsius?

**Comment by sfrcorne** [comment]
I'm also on a Ryzen 5 7600X using its iGPU (no dGPU atm), and some values in Mangohud do not display the correct value:
1) `cpu_temp` : 655C
2) `cpu_power` : 66W
3) `gpu_core_clock` : 65535MHz
4) `gpu_mem_clock` : 65535MHz

These 4 values are fixed and do not change over time. All other cpu and gpu values seem to work correctly as far as I can tell.

The output of the following commands are:
1) `grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_label'`
- Tctl
2) `grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_input'`
- 45125
3) `sensors | grep Tctl`
- Tctl:         +45.1°C

I ran the last two commands as:
`grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_input' && sensors | grep Tctl`
While the values change over time, they both return the same value if you assume the first number is in milli-Celsius.

Kernel Version: `6.1.5-arch2-1`
Mangohud Version: `flatpak 0.6.8`

**Comment by gort818** [comment]
I just pushed a commit that should fix the temperature reporting for zen4.

**Comment by Daniel-Salvado** [comment]
Temperature does show for me in-game ([screenshot](https://imgur.com/a/L5QCg5L)) but the power consumption has always been zero. Is this expected or should I create a separate issue?

**Comment by gort818** [comment]
Yes that is expected k10temp dropped support for that. 
For older amd cpus you can use the zenpower3 kernel module. Don't believe there is zen4 support yet.

**Comment by TateFleming** [comment]
I'm still seeing 655 CPU temp reported.

**Comment by sfrcorne** [comment]
I installed `mangohud-git` and tested the patch and I can confirm that the issue is not yet fixed. The temperature `cpu_temp` still shows 655C.

**Comment by gort818** [comment]
> I installed `mangohud-git` and tested the patch and I can confirm that the issue is not yet fixed. The temperature `cpu_temp` still shows 655C.

Does this output anything for you
` grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_input'`

**Comment by sfrcorne** [comment]
> I'm also on a Ryzen 5 7600X using its iGPU (no dGPU atm), and some values in Mangohud do not display the correct value:
> 
>     1. `cpu_temp` : 655C
> 
>     2. `cpu_power` : 66W
> 
>     3. `gpu_core_clock` : 65535MHz
> 
>     4. `gpu_mem_clock` : 65535MHz
> 
> 
> These 4 values are fixed and do not change over time. All other cpu and gpu values seem to work correctly as far as I can tell.
> 
> The output of the following commands are:
> 
>     1. `grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_label'`
> 
> 
>     * Tctl
> 
> 
>     2. `grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_input'`
> 
> 
>     * 45125
> 
> 
>     3. `sensors | grep Tctl`
> 
> 
>     * Tctl:         +45.1°C
> 
> 
> I ran the last two commands as: `grep -rl "k10temp" /sys/class/hwmon/* 2>/dev/null | xargs -I{} sh -c 'cd "$(dirname "{}")"; cat temp1_input' && sensors | grep Tctl` While the values change over time, they both return the same value if you assume the first number is in milli-Celsius.
> 
> Kernel Version: `6.1.5-arch2-1` Mangohud Version: `flatpak 0.6.8`

Yup, still the same output as 2 days ago. See my comment of two day ago above in reply.

**Comment by gort818** [comment]
Oops sorry ok I will look into this, can you build debug version and post the output

**Comment by sfrcorne** [comment]
Sorry for the delay. I had some problems building the debug version. Hopefully, it build correctly. Below, inside the spoiler, is the output of `mangohud glxgears`.

<details>
  <summary>SPOILER: OUTPUT</summary>

```
[2023-01-17 22:59:44.048] [MANGOHUD] [info] [config.cpp:118] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2023-01-17 22:59:44.048] [MANGOHUD] [info] [config.cpp:118] skipping config: '/home/sfrcorne/.config/MangoHud/glxgears.conf' [ not found ]
[2023-01-17 22:59:44.048] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/sfrcorne/.config/MangoHud/MangoHud.conf'
[2023-01-17 22:59:44.048] [MANGOHUD] [debug] [logging.cpp:168] Logger constructed!
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [overlay.cpp:888] Ram:31999032
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [overlay.cpp:889] Cpu:AMD Ryzen 5 7600X 6-Core Processor
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [overlay.cpp:890] Kernel:6.1.6-arch1-3
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [overlay.cpp:891] Os:EndeavourOS
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [overlay.cpp:892] Driver:4.6 Mesa 22.3.3
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [overlay.cpp:893] CPU Scheduler:schedutil
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:433] hwmon: sensor name: hidpp_battery_1
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:433] hwmon: sensor name: amdgpu
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:433] hwmon: sensor name: nvme
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:433] hwmon: sensor name: hidpp_battery_0
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:433] hwmon: sensor name: k10temp
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:457] hwmon: using input: /sys/class/hwmon/hwmon1/temp1_input
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:550] hwmon: sensor name: hidpp_battery_1
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:550] hwmon: sensor name: amdgpu
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:550] hwmon: sensor name: nvme
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:550] hwmon: sensor name: hidpp_battery_0
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:550] hwmon: sensor name: k10temp
[2023-01-17 22:59:44.081] [MANGOHUD] [debug] [gl_hud.cpp:125] deviceName: AMD Radeon Graphics (gfx1036, LLVM 14.0.6, DRM 3.49, 6.1.6-arch1-3)
[2023-01-17 22:59:44.081] [MANGOHUD] [debug] [overlay.cpp:713] drm path check: /sys/class/drm/card0
[2023-01-17 22:59:44.081] [MANGOHUD] [debug] [overlay.cpp:753] Using gpu_metrics of /sys/class/drm/card0/device/gpu_metrics
[2023-01-17 22:59:44.081] [MANGOHUD] [info] [overlay.cpp:798] Uploading is disabled (permit_upload = 0)
[2023-01-17 22:59:44.087] [MANGOHUD] [debug] [gl_hud.cpp:140] gpu: Raphael
[2023-01-17 22:59:44.087] [MANGOHUD] [info] [gl_renderer.cpp:422] GL version: 4.6 
[2023-01-17 22:59:44.099] [MANGOHUD] [debug] [inject_glx.cpp:105] GL ref count: 1
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
[2023-01-17 22:59:44.101] [MANGOHUD] [debug] [gl_renderer.cpp:296] glsl_version: 410
306 frames in 5.0 seconds = 61.001 FPS
301 frames in 5.0 seconds = 60.001 FPS
X connection to :1 broken (explicit kill or server shutdown).
```
</details>

**Comment by gort818** [comment]
Is this the correct file for your CPU temp

```
[debug] [cpu.cpp:433] hwmon: sensor name: k10temp
[2023-01-17 22:59:44.080] [MANGOHUD] [debug] [cpu.cpp:457] hwmon: using input: /sys/class/hwmon/hwmon1/temp1_input
```

**Comment by sfrcorne** [comment]
Yes, it appears to be the correct file. It gives the same output as reported by `sensors | grep Tctl`

**Comment by sfrcorne** [comment]
I added some more debug line to the code and I think I found where the problem is in `cpu.cpp`.

The first time the function:

`[249] bool CPUStats::UpdateCpuTemp() {`

is called, the temperature is set correctly. However all other times the function is called, `cpu_type == "APU"` so that the temperature is not set correctly. Changing the **if** condition so that it goes into the **else**-statment, update and displays the temperature correctly.

The remaining question now of course is: Why and Where is `cpu_type` set incorrectly to  "APU" instead of "CPU"?

**Comment by gort818** [comment]
Yep, saw that. So technically it is a apu, the relevant code is in amdgpu.cpp. if you could send me the gpu_metrics file that would be great.

**Comment by sfrcorne** [comment]
[gpu_metrics.tar.gz](https://github.com/flightlessmango/MangoHud/files/10460833/gpu_metrics.tar.gz)

Here is the file.

**Comment by gort818** [comment]
Hmm well here is the output of the file
```
temperature_gfx: 120
temperature_soc: 258
temperature_core[8]: 65535
temperature_l3[2]: 65535
average_gfx_activity: 65535
average_mm_activity: 65535
system_clock_counter: 385133925728
average_socket_power: 36717
average_cpu_power: 65535
average_soc_power: 16638
average_gfx_power: 9798
average_core_power[8]: 600
average_gfxclk_frequency: 600
average_socclk_frequency: 1200
average_uclk_frequency: 2800
average_fclk_frequency: 2800
average_vclk_frequency: 400
average_dclk_frequency: 300
current_gfxclk: 65535
current_socclk: 65535
current_uclk: 65535
current_fclk: 65535
current_vclk: 65535
current_dclk: 65535
current_coreclk[8]: 65535
current_l3clk[2]: 0
throttle_status: 0
fan_pwm: 65535
```
So nothing really looks right.

**Comment by flightlessmango** [comment]
Looks like we're doing the right thing but the kernel driver hasn't fixed this yet or it's a bug on their end.
Should be reported here https://gitlab.freedesktop.org/drm/amd/-/issues

**Comment by sfrcorne** [comment]
I don't think the file is read in correctly. Reading the `header` I get:

1) `structure_size` : 120
2) `format_revision` : 2
3) `content_revision` : 1

Since `sizeof(gpu_metrics_v1_3)` is 120 and `sizeof(gpu_metrics_v2_2)` is 128, it appears that this file is neither v1_3 or v2_2 but v2_1. It tries to use v2_2 instead, so is v2_1 compatible with v2_2?

**Comment by flightlessmango** [comment]
Yes they are compatible, you should always use the latest.
v2_3 exists now so we might want to use that.
But it wouldn't fix this issue

**Comment by sfrcorne** [comment]
So I have looked at the source code of the kernel driver, and I don't think this is a bug on their end. The code that is probably responsible for setting the `gpu_metrics` file on Ryzen 7000 CPU can be found here:

https://elixir.bootlin.com/linux/latest/source/drivers/gpu/drm/amd/pm/swsmu/smu13/smu_v13_0_5_ppt.c#L459

As you can see, the only values that are set in the `gpu_metrics` file are: `temperature_gfx`, `temperature_soc`, `average_gfx_activity`, `average_mm_activity`, `average_socket_power`, `average_gfx_power`, `average_soc_power`, `average_gfxclk_frequency`, `average_socclk_frequency`, `average_uclk_frequency`, `average_fclk_frequency`, `average_vclk_frequency`, `average_dclk_frequency`, `throttle_status` & `system_clock_counter`. That is it, so we will have to work with those values. All other values are set to 0xFFFF (all bits are 1 or 65535 in decimal) by memset() in:

https://elixir.bootlin.com/linux/latest/source/drivers/gpu/drm/amd/pm/swsmu/smu_cmn.c#L999

This indeed corresponds with the `gpu_metrics` file I get while debugging MangoHud.

So to fix the values reported by MangoHud on amd Ryzen 7000 CPU while using its iGPU, I added some new fallback method that uses the `average_xxx` values instead of the `current_xxx` ones if those are not available. I also added some other fallback methods just in case this might help other Ryzen APU's. I will make a pull-request shortly.

**Comment by flightlessmango** [comment]
So they aren't pushing all the data yet? So it's on their end to fix then?

**Comment by gort818** [comment]
I just installed a 7900x, if not using the iGPU I have no issues with temperature reporting. The iGPU shouldn't be used for gaming anyway.

**Comment by melroy89** [comment]
See also: https://github.com/flightlessmango/MangoHud/issues/147 (which is already closed.. but not fixing the problem)

Please, reopen. This issue is still not resolved in the latest release (v0.6.9-1).

The `sensors` command will show the temps just fine (Intel i7 processor):

```
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +43.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:       +43.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:       +43.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:       +41.0°C  (high = +80.0°C, crit = +100.0°C)
```

And: `cat /sys/class/hwmon/hwmon*/name` will give:
```
amdgpu
atk0110
coretemp
```

You need to use the **coretemp** module here! In order to retrieve the CPU temps in my case.

**Comment by flightlessmango** [comment]
We're already checking for and using coretemp
https://github.com/flightlessmango/MangoHud/blob/master/src/cpu.cpp#L442

**Comment by melroy89** [comment]
@flightlessmango Sorry my bad! You are right.. CPU is fine.. It gave an error about CPU power: `[2023-04-22 18:06:57.526] [MANGOHUD] [error] [cpu.cpp:568] Failed to initialize CPU power data` instead.

Maybe I'm missing a dependency, missing feature or simply because this CPU can't read-out the power data.

**Comment by flightlessmango** [comment]
@melroy89 for intel CPUs we can't fetch power usage without some permissions.
It's described in the readme how to fix this, at the bottom of the Environment Variables section
